// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AnimationController from "./animation_controller"
application.register("animation", AnimationController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import GptResponseController from "./gpt_response_controller"
application.register("gpt-response", GptResponseController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import WeatherDisplayController from "./weather_display_controller"
application.register("weather-display", WeatherDisplayController)
